
[2019-09-25 13:51:31] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 13:57:24] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 13:58:04] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 14:21:09] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 14:21:15] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 14:21:36] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 14:23:05] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 14:23:11] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 15:12:20] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.bind("<Configure>",self.paned_window_resized)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1251, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1206, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed


[2019-09-25 15:17:51] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.add("<Configure>",self.paned_window_resized)
TypeError: add() takes 2 positional arguments but 3 were given


[2019-09-25 15:18:23] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 57, in create_widgets
    self.paned_window.add(self.map)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3823, in add
    self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: invalid command name ".!application.!panedwindow2"


[2019-09-25 15:20:08] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 59, in create_widgets
    self.paned_window.add(self.canvas)
AttributeError: 'Application' object has no attribute 'canvas'


[2019-09-25 15:23:21] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self.paned_window)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 66, in __init__
    mainWindow.paned_window.add(app)
AttributeError: 'PanedWindow' object has no attribute 'paned_window'


[2019-09-25 15:24:36] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self.paned_window)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 59, in __init__
    app = MainFrame(mainWindow)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 75, in __init__
    root.geometry("900x640")
AttributeError: 'PanedWindow' object has no attribute 'geometry'


[2019-09-25 15:25:27] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self.paned_window)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 59, in __init__
    app = MainFrame(mainWindow.master)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 75, in __init__
    root.geometry("900x640")
AttributeError: 'Application' object has no attribute 'geometry'


[2019-09-25 15:27:07] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 61, in __init__
    app = MainFrame(mainWindow.master)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 61, in __init__
    app = MainFrame(mainWindow.master)
  File "/usr/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit


[2019-09-25 15:27:34] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 61, in __init__
    app = MainFrame(mainWindow.master)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 61, in __init__
    app = MainFrame(mainWindow.master)
  File "/usr/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit


[2019-09-25 15:28:01] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 59, in __init__
    app = MainFrame(mainWindow)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 75, in __init__
    root.geometry("900x640")
AttributeError: 'Application' object has no attribute 'geometry'


[2019-09-25 15:28:21] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 66, in __init__
    mainWindow.paned_window.add(app)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3823, in add
    self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: invalid command name ".!application.!panedwindow2"


[2019-09-25 15:28:54] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 59, in __init__
    app = MainFrame(mainWindow)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 81, in __init__
    self.master.title("Tkinter example")
AttributeError: 'Application' object has no attribute 'title'


[2019-09-25 15:29:22] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 59, in __init__
    app = MainFrame(mainWindow)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 82, in __init__
    self.master.protocol("WM_DELETE_WINDOW", self.on_close)
AttributeError: 'Application' object has no attribute 'protocol'


[2019-09-25 15:30:01] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 66, in __init__
    mainWindow.paned_window.add(app)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3823, in add
    self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: invalid command name ".!application.!panedwindow2"


[2019-09-25 15:31:17] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 66, in __init__
    mainWindow.paned_window.add(app)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3823, in add
    self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: invalid command name ".!application.!panedwindow2"


[2019-09-25 15:59:51] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 59, in __init__
    app = MainFrame(mainWindow)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 80, in __init__
    tk.Frame.__init__(self, parent = root)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2744, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-parent"


[2019-09-25 23:18:54] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 66, in __init__
    mainWindow.paned_window.add(app)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3823, in add
    self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: invalid command name ".!application.!panedwindow2"


[2019-09-26 00:04:46] Traceback (most recent call last):
  File "TaskerGui.py", line 93, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 55, in create_widgets
    self.map = TaskerMap(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 66, in __init__
    mainWindow.paned_window.add(app)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3823, in add
    self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: invalid command name ".!application.!panedwindow2"


[2019-09-26 00:24:26] Traceback (most recent call last):
  File "TaskerMap.py", line 396, in <module>
    app = MainFrame(root)
  File "TaskerMap.py", line 97, in __init__
    self.browser_frame = BrowserFrame(self, self.navigation_bar)
  File "TaskerMap.py", line 161, in __init__
    self.embed_browser()
  File "TaskerMap.py", line 170, in embed_browser
    url="file:///J:\q.htm") #todo
  File "cefpython_py36.pyx", line 682, in cefpython_py36.CreateBrowserSync
AssertionError: cefpython.CreateBrowserSync() may only be called on the UI thread


[2019-09-26 00:32:54] Traceback (most recent call last):
  File "TaskerMap.py", line 402, in <module>
    app.mainloop()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/bdb.py", line 55, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/lib/python3.6/bdb.py", line 99, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit


[2019-09-26 12:37:24] Traceback (most recent call last):
  File "load_handler.pyx", line 40, in cefpython_py36.LoadHandler_OnLoadStart
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 267, in OnLoadStart
    if self.browser_frame.master.navigation_bar:
AttributeError: 'Application' object has no attribute 'navigation_bar'


[2019-09-26 12:41:21] Traceback (most recent call last):
  File "TaskerGui.py", line 97, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 58, in create_widgets
    self.map = BrowserFrame(self)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 174, in __init__
    self.navigation_bar = NavigationBar(master)
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 340, in __init__
    self.update_state()
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 375, in update_state
    browser = self.master.get_browser()
AttributeError: 'Application' object has no attribute 'get_browser'


[2019-09-26 12:46:45] Traceback (most recent call last):
  File "load_handler.pyx", line 40, in cefpython_py36.LoadHandler_OnLoadStart
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 267, in OnLoadStart
    if self.browser_frame.master.navigation_bar:
AttributeError: 'Application' object has no attribute 'navigation_bar'


[2019-09-26 12:47:21] Traceback (most recent call last):
  File "load_handler.pyx", line 40, in cefpython_py36.LoadHandler_OnLoadStart
  File "/home/ahchen0/Documents/Tasker/TaskerGui/TaskerMap.py", line 268, in OnLoadStart
    if self.browser_frame.master.navigation_bar:
AttributeError: 'Application' object has no attribute 'navigation_bar'


[2019-09-26 13:10:37] Traceback (most recent call last):
  File "TaskerGui.py", line 98, in <module>
    App=Application(master=root)
  File "TaskerGui.py", line 27, in __init__
    self.create_widgets()
  File "TaskerGui.py", line 60, in create_widgets
    self.paned_window.bind("<Configure>", self.paned_window.resized)
AttributeError: 'PanedWindow' object has no attribute 'resized'

